=== gbuh/EPAM_Task3/XMLPlane/PlaneCatalogue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.example.org/planes"
		xmlns:tns="http://www.example.org/planes" elementFormDefault="qualified">

	<element name="planes">
		<complexType>
			<sequence>
				<element name="plane" type="tns:plane" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="plane">
		<sequence>
			<element name="model" type="string" />
			<element name="origin" type="string" />
			<element name="price" type="tns:price" />
			<element name="chars" type="tns:chars" />
			<element name="parameters" type="tns:parameters" />
		</sequence>
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="ID">
					<pattern value="[a-zA-z0-9_]+" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="price">
		<simpleContent>
			<extension base="positiveInteger">
				<attribute name="currency" type="string" fixed="Thaler" />
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="chars">
		<sequence>
			<element name="type" type="tns:type" minOccurs="0" />
			<element name="places" type="tns:places" minOccurs="0" />
			<element name="ammunition" type="tns:ammunition" minOccurs="0" />
			<element name="radar" type="boolean" minOccurs="0" />
		</sequence>
	</complexType>

	<simpleType name="type">
		<restriction base="string">
			<enumeration value="Support Aircraft" />
			<enumeration value="Escort Aircraft" />
			<enumeration value="Fighter" />
			<enumeration value="Interceptor" />
			<enumeration value="Scout" />
		</restriction>
	</simpleType>

	<simpleType name="places">
		<restriction base="byte">
			<minInclusive value="1" />
			<maxInclusive value="2" />
		</restriction>
	</simpleType>

	<complexType name="ammunition">
		<simpleContent>
			<extension base="boolean">
				<attribute name="rockets" type="tns:rockets" use="optional" />
			</extension>
		</simpleContent>
	</complexType>

	<simpleType name="rockets">
		<restriction base="byte">
			<minInclusive value="0" />
			<maxInclusive value="10" />
		</restriction>
	</simpleType>

	<complexType name="parameters">
		<sequence>
			<element name="length" type="float" />
			<element name="width" type="float" />
			<element name="height" type="float" />
		</sequence>
		<attribute name="measure" type="string" default="meters" />
	</complexType>
</schema>

=== gbuh/EPAM_Task3/XMLPlane/PlaneCatalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML-document. This XML is valid for the PlaneCatalogue.xsd XML-schema-->

<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.example.org/planes"
		xsi:schemaLocation="http://www.example.org/planes PlaneCatalogue.xsd">
	
	<plane id="plane1">
		<model>CF5D</model>
		<origin>USA</origin>
		<price currency="Thaler">350000</price>
		<chars>
			<type>Support Aircraft</type>
			<places>2</places>
			<ammunition rockets="4">true</ammunition>
			<radar>true</radar>
		</chars>
		<parameters measure="meters">
			<length>15.65</length>
			<width>10.11</width>
			<height>3.09</height>
		</parameters>
	</plane>
	<plane id="plane2">
		<model>AERO L-39C ALBATROS</model>
		<origin>Canada</origin>
		<price currency="Thaler">410000</price>
		<chars>
			<type>Scout</type>
			<places>1</places>
			<ammunition>false</ammunition>
			<radar>false</radar>
		</chars>
		<parameters measure="meters">
			<length>14</length>
			<width>9.5</width>
			<height>3.16</height>
		</parameters>
	</plane>
		<plane id="plane3">
		<model>CY25</model>
		<origin>RUSSIA</origin>
		<price currency="Thaler">500000</price>
		<chars>
			<type>Fighter</type>
			<places>1</places>
			<ammunition rockets="10">true</ammunition>
			<radar>true</radar>
		</chars>
		<parameters measure="meters">
			<length>17.20</length>
			<width>10.50</width>
			<height>3.30</height>
		</parameters>
	</plane>
</planes>
